---
- hosts: localhost
  vars:
      URL_GIT: https://github.com/robsonvitor/ansible-meu-desktop.git
      sha256sum_ansible_pull: "ef7523d944b9cc2e19e8450fbe08f638107293a34d0d5eef1a9826f7d256b34a"
  pre_tasks:
    - name: Atualizando repositórios e pacotes instalados
      apt:
        update_cache: yes
        upgrade: safe
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/crontab.yml
