---
- name: Remover arquivo antigo
  file:
    path: /etc/crond.d/ansible-pull
    state: absent

  #- name: Removes a cron file from under /etc/cron.d
  #cron:
  #  cron_file: ansible-pull
  #  state: absent

- name: Agendamento de tarefas /etc/cron.d
  cron:
    special_time: daily
    user: root
    job: "/usr/bin/ansible-pull -o -U {{ URL_GIT }}"
    cron_file: ansible-pull
  tags: cron
