---
- name: Atributos do arquivo
  stat:
    path: /etc/cron.d/ansible-pull
  register: status_arquivo

- name: Copiar o arquivo correto
  copy:
    src: ./arquivos/ansible-pull
    dest: /etc/cron.d/ansible-pull
  when: status_arquivo.stat.checksum != "{{ checksum_ansible_pull }}"
